import type { Metadata } from "next";
import { Inter, Architects_Daughter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Architects = Architects_Daughter({
  subsets: ["latin"],
  weight: "400",
  variable: "--daughter",
});
export const metadata: Metadata = {
  title: "Jason Morrissette || Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Architects.variable}`}>
        {children}
      </body>
    </html>
  );
}
